### ISSUE TITLE
Can you help solve this?

### ISSUE THREAD

**Issue by preetd14** [prakharcode/yolo-server#3]
Traceback (most recent call last):
  File "./yad2k.py", line 25, in <module>
    from yad2k.models.keras_yolo import (space_to_depth_x2,
  File "/home/preetderasari/yolo-server-master/yad2k.py", line 25, in <module>
    from yad2k.models.keras_yolo import (space_to_depth_x2,
ModuleNotFoundError: No module named 'yad2k.models'; 'yad2k' is not a package

**Comment by adrianblazquez** [comment]
The same is happening to me. . .
